#! /bin/bash

set -e 

#### Video Driver
##
##### Modern AMD
##
##Add `amdgpu` to MODULES in `/etc/mkinitcpio.conf`
##
##Install the X driver and (re)generate the boot image:
##
##`pacman -S xf86-video-amdgpu libva-mesa-driver linux`
##
##### Intel Only (lightweight laptop)
##
##`pacman -S xf86-video-intel libva-intel-driver`
##

yes | pacman -S xf86-video-intel libva-intel-driver

##### Nvidia Only (desktop)
##
##Unfortunately, the nouveau drivers aren't feature complete or performant, so use the dirty, proprietary ones. Linus extends the middle finger to nvidia.
##
##`pacman -S nvidia nvidia-settings`
##


##### Nvidia + Intel (heavy laptop)
##
##I don't need the nvidia discrete GPU for a work laptop, so completely disable it.
##
##If the discrete GPU is needed, optimus/prime may be used to enable it on demand.
##
##`pacman -S xf86-video-intel libva-intel-driver bbswitch`
##
##Load the bbswitch module via `/etc/modules-load.d/bbswitch.conf`:
##
##```
##bbswitch
##```
##
##Disable/enable the GPU on module load/unload via `/etc/modprobe.d/bbswitch.conf`:
##
##```
##options bbswitch load_state=0 unload_state=1
##```
##
##Ban the nouveau module, which can block bbswitch, via `/etc/modprobe.d/blacklisted.conf`:
##
##```
##blacklist nouveau
##```
##