#! /bin/bash

set -e 

##```sh
##cd /tmp
##git clone https://aur.archlinux.org/aura-bin.git
##cd aura-bin
##makepkg -sri
##```

mkaura () {
	mkdir $HOME/tmp
	cd $HOME/tmp
	git clone https://aur.archlinux.org/aura-bin.git
	cd aura-bin
	makepkg -sri
}

if [[ ! $(whereis aura) ]]; then
	sudo -u "$SUDO_USER" mkaura
fi

aura -Ax \
	gron-bin \
	j4-dmenu-desktop \
	qdirstat \
	pulseaudio-ctl \
	redshift-minimal \
	ttf-ms-fonts \
	xlayoutdisplay \
	xf86-input-libinput \
	intellij-idea-ultimate-edition \
	networkmanager-dmenu-git \
	libinput-gestures \
	slack-desktop \
	google-chrome
	
