#! /bin/bash

set -e 

if [[ $EUID -eq 0 ]]; then
	echo "Don't run this script as root"
	exit 1
fi

if [[ ! $(stack --version) ]]; then 
	curl -sSL https://get.haskellstack.org/ | sh
	stack setup
fi

if [[ ! -e $HOME/.xmonad/xmonad-git/.git ]]; then
	git clone "https://github.com/xmonad/xmonad" $HOME/.xmonad/xmonad-git
else
	pushd .
	cd $HOME/.xmonad/xmonad-git
	git pull
	popd
fi

if [[ ! -e $HOME/.xmonad/xmonad-contrib-git/.git ]]; then
	git clone "https://github.com/xmonad/xmonad-contrib" $HOME/.xmonad/xmonad-contrib-git
else
	pushd .
	cd $HOME/.xmonad/xmonad-contrib-git
	git pull
	popd
fi

if [[ ! -e $HOME/.xmonad/xmobar-git/.git ]]; then
	git clone "https://github.com/jaor/xmobar" $HOME/.xmonad/xmobar-git
else
	pushd .
	cd $HOME/.xmonad/xmobar-git
	git pull
	popd
fi

if [[ ! -e $HOME/.xmonad/stack.yml ]]; then
	mkdir -p $HOME/.xmonad
	cd $HOME/.xmonad
	stack init
	cd -
fi

curl https://raw.githubusercontent.com/keynan/arch/8b7f316264ad541f8c8a31ccf31650f908ca836d/home/.xmonad/xmonad.hs > $HOME/.xmonad/xmonad.hs
curl https://raw.githubusercontent.com/keynan/arch/8b7f316264ad541f8c8a31ccf31650f908ca836d/home/.xmobarrc > $HOME/.xmobarrc
curl https://raw.githubusercontent.com/keynan/arch/8b7f316264ad541f8c8a31ccf31650f908ca836d/home/.xinitrc > $HOME/.xinitrc

if [[ ! -e $HOME/.xmonad/stack.yml.bak ]]; then
	cp $HOME/.xmonad/stack.yml $HOME/.xmonad/stack.yml.bak
fi
cat $HOME/.xmonad/stack.yml.bak | grep -v ^# > $HOME/.xmonad/stack.yml
cat > $HOME/.xmonad/stack.yml <<EOF
extra_deps:
  - iwlib-0.1.0
flags:
  xmobar:
    all_extensions: true
extra-package-dbs: []
EOF

stack install

cat > $HOME/.xmonad/build <<EOF
exec stack ghc -- \
  --make xmonad.hs \
  -i \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 \
  -o "$1"
EOF
chmod a+x $HOME/.xmonad/build

xmonad --recompile
