#! /bin/bash

set -e

aura -A \
  nvm 

if [[ ! $(grep NVM_DIR $HOME/.zshrc) ]]; then
cat > $HOME/.zshrc <<EOF
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
source /usr/share/nvm/nvm.sh
source /usr/share/nvm/bash_completion
source /usr/share/nvm/install-nvm-exec
EOF
fi
