#! /bin/bash

set -e

yes | pacman -S docker docker-compose

if [[ ! $(cut -d: -f1 /etc/group | grep docker) ]]; then
    groupadd docker
fi
usermod -aG docker $SUDO_USER

echo '{"default-address-pools":[{"base":"10.255.0.0/16","size":24}]}' >> /etc/docker/daemon.json

systemctl enable docker
systemctl start docker

