#! /bin/bash

set -e

## Edit `/etc/pacman.d/mirrorlist` and put a local one on top
##
## `pacstrap -i /mnt base base-devel`

if [[ ! -e /etc/pacman.d/mirrorlist.bak ]]; then
	cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
fi

cat > /etc/pacman.d/mirrorlist <<EOF
## Australia servers are all fucked
Server = http://mirror.internode.on.net/pub/archlinux/$repo/os/$arch
Server = http://archlinux.melbourneitmirror.net/$repo/os/$arch
Server = http://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch
Server = http://ftp.iinet.net.au/pub/archlinux/$repo/os/$arch
Server = http://ftp.swin.edu.au/archlinux/$repo/os/$arch

EOF
cat /etc/pacman.d/mirrorlist.bak >> /etc/pacman.d/mirrorlist
mkdir -p /mnt/etc/pacman.d/
cp -f /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist

# take all default confim dialogs
pacstrap -i /mnt base base-devel git <<EOF




EOF

